bundler_args: "--without development"
rvm:
  - 1.9.3
  - 2.0.0
language: ruby
before_script:
  - cd spec/dummy_app
  - bundle install
  - bundle exec rake rails_admin:prepare_ci_env db:create db:migrate
  - cd ../../
